image:
  file: .gitpod.Dockerfile

ports:
  - name: Grafana
    port: 3000
    protocol: http
    visibility: public
    onOpen: ignore
  - name: Health check
    port: 8040
    onOpen: ignore
  - name: Lunar Proxy
    port: 8080
    onOpen: ignore
  - name: Prometheus
    port: 9090
    onOpen: ignore
  - name: Provider
    port: 4578
    onOpen: ignore
  - name: Consumer
    port: 7897
    onOpen: ignore

tasks:
  - name: Sandbox Terminal
    command: |
      cp ${GITPOD_REPO_ROOT}/scenarios/${SANDBOX_SCENARIO} ${GITPOD_REPO_ROOT}/policies.yaml
      open ${GITPOD_REPO_ROOT}/policies.yaml
      cd /home/gitpod
      SANDBOX_SCENARIO=${SANDBOX_SCENARIO} POLICIES_DIR=${GITPOD_REPO_ROOT} docker compose --project-name sandbox up -d --wait --wait-timeout 60
      curl --silent --output /dev/null -H "Content-Type: application/json" -d '{"scheme": "http", "host": "provider:4578", "path": "/rate-limit/exponential-backoff", "method": "GET", "sleep_ms": 5}' http://localhost:7897/traffic
      gp ports await 3000

      if [[ "${SANDBOX_SCENARIO}" == "strategy_based_throttling" ]]; then
        gp preview $(gp url 3000)/d/d2c76c83-9968-4ef6-a6a5-6105e661f9bf/lunar-sandbox
      else if [[ "${SANDBOX_SCENARIO}" == "quota_allocation" ]]; then
        gp preview $(gp url 3000)/d/d0820680-9427-487d-ac2e-954318bc6cec/lunar-sandbox
      fi
